### ISSUE TITLE
Request: Could a current tag and release be posted on GitHub?

### ISSUE THREAD

**Issue by dcslagel** [robauto/bibli3.0#4]
Could a current tag and release be posted on GitHub?

**Comment by robauto** [comment]
Not sure what you mean?

**Comment by dcslagel** [comment]
@robauto,  An example of releases can be seen in at this project. 
https://github.com/kinverarity1/lasio
On the right side below the `About` section is the `Release` section 
https://github.com/kinverarity1/lasio/releases/tag/v0.28
Here one can click on a release link , see the change list and download a gzip/zip file of the code.  This is a well know and standard release location.

To create a release:
1. Add or update a CHANGELOG.md at the root of the directory with what has changed in the release.
Example:    
https://github.com/dcslagel/las-util-cpp/blob/master/CHANGELOG.md
2. Update the README.md for the release if needed.
3. Create a Git Tag on the most recent commit.  GitHub will use this tag to generate the gzip/zip files and release version number.
Example in local git repo:    
```bash
git tag -a v3.0.0 -m"Initial release package of existing functionality"
git push
git push origin v3.0.0
```
4. On GitHub, go to https://github.com/robauto/bibli3.0/tags  find the current tag and select or create the related release. Update the release markup.  Then the release will generate a gzip and a zip package from the repo for this release.

**Comment by dcslagel** [comment]
This is over a year old and not active, so closing for now. It can be reopened in the future if needed.

DC
